name = "Akash Website"
license = "MIT"
licenselink = "https://github.com/akash-network/website/blob/main/LICENSE"
description = "Akash Network Website Theme"

homepage = "https://github.com/akash-network/website"
demosite = "https://akash.network"

[author]
  name = "Greg Osuri"
  homepage = "https://gregosuri.com"